# Project Information
site_name: dbtc
site_description: An unaffiliated python wrapper for dbt Cloud APIs
site_author: Doug Guthrie

# Repository
repo_name: dbtc
repo_url: https://github.com/dpguthrie/dbtc

# Configuration
theme:
  name: material
  palette:
    primary: deep orange
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo-white.png
  favicon: img/logo-white.png
  language: en

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dpguthrie
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/douglas-guthrie-07994a48/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@douglas.p.guthrie
    - icon: fontawesome/solid/globe
      link: https://dpguthrie.com

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Navigation
nav:
  - index.md

# Google Analytics
google_analytics:
  - UA-174219875-1
  - auto

# Plugins
plugins:
  - search