name: Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install_dev
    - name: Run tests and coverage
      run: make test_cov
      env:
        DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
        DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
        DBT_CLOUD_ACCOUNT_NAME: ${{ secrets.DBT_CLOUD_ACCOUNT_NAME }}
        DBT_CLOUD_PROJECT_NAME: ${{ secrets.DBT_CLOUD_PROJECT_NAME }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
