name: Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: make install_dev

    - name: Run tests and coverage
      run: make test_cov
      env:
        DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
        DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
        DBT_CLOUD_ACCOUNT_NAME: ${{ secrets.DBT_CLOUD_ACCOUNT_NAME }}
        DBT_CLOUD_PROJECT_NAME: ${{ secrets.DBT_CLOUD_PROJECT_NAME }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
